from conda/miniconda3:latest
LABEL author="wmx"

RUN apt update

RUN apt install -y nginx supervisor
RUN pip install gunicorn
RUN pip install gevent
RUN pip install setuptools
RUN pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
RUN pip install paddlehub -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN hub install deeplabv3p_xception65_humanseg

ENV PYTHONIOENCODING=utf-8
#设置东8区
ENV TIME_ZONE="Asia/Shanghai"
RUN ln -snf /usr/share/zoneinfo/$TIME_ZONE /etc/localtime && echo "$TIME_ZONE" > /etc/timezone

#RUN pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
# Build folder
RUN mkdir -p /deploy/app
WORKDIR /deploy/app
COPY requirements.txt /deploy/app/requirements.txt
RUN pip install -r /deploy/app/requirements.txt  -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
# Setup nginx
RUN rm /etc/nginx/sites-enabled/default
COPY nginx_flask.conf /etc/nginx/sites-available/
RUN ln -s /etc/nginx/sites-available/nginx_flask.conf /etc/nginx/sites-enabled/nginx_flask.conf
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

# Setup supervisord
RUN mkdir -p /var/log/supervisor
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# run sh. Start processes in docker-compose.yml
#CMD ["/usr/bin/supervisord"]
CMD ["/bin/bash"]
